export default[
    {
        "theme": "light",
        "color-scheme": "light",
        "primary": "#6200EA",
        "primary-content": "#FFFFFF",
        "secondary": "#03DAC6",
        "accent": "#03A9F4",
        "neutral": "#F5F5F5",
        "base-100": "#FFFFFF",
        "info": "#2196F3",
        "success": "#4CAF50",
        "warning": "#FF9800",
        "error": "#F44336"
    },
    {
        "theme": "dark",
        "color-scheme": "dark",
        "primary": "#BB86FC",
        "primary-content": "#000000",
        "secondary": "#03DAC6",
        "accent": "#FF0266",
        "neutral": "#121212",
        "base-100": "#1F1F1F",
        "info": "#2196F3",
        "success": "#4CAF50",
        "warning": "#FFC107",
        "error": "#CF6679"
    },
    {
      "theme": "cupcake",
      "color-scheme": "light",
      "primary": "#65c3c8",
      "primary-content": "#FFFFFF",
      "secondary": "#ef9fbc",
      "accent": "#fae3b0",
      "neutral": "#a7a9be",
      "base-100": "#f3f4f6",
      "info": "#3abff8",
      "success": "#36d399",
      "warning": "#fbbd23",
      "error": "#f87272"
    },
    {
      "theme": "emerald",
      "color-scheme": "light",
      "primary": "#10b981",
      "primary-content": "#FFFFFF",
      "secondary": "#34d399",
      "accent": "#d946ef",
      "neutral": "#111827",
      "base-100": "#f9fafb",
      "info": "#3b82f6",
      "success": "#22c55e",
      "warning": "#f59e0b",
      "error": "#ef4444"
    },
    {
      "theme": "synthwave",
      "color-scheme": "dark",
      "primary": "#f72585",
      "primary-content": "#FFFFFF",
      "secondary": "#b5179e",
      "accent": "#7209b7",
      "neutral": "#1d1d1d",
      "base-100": "#2a2a2a",
      "info": "#3a86ff",
      "success": "#8338ec",
      "warning": "#ffbe0b",
      "error": "#fb5607"
    },
    {
      "theme": "forest",
      "color-scheme": "light",
      "primary": "#388E3C",
      "primary-content": "#FFFFFF",
      "secondary": "#4CAF50",
      "accent": "#FF9800",
      "neutral": "#C8E6C9",
      "base-100": "#E8F5E9",
      "info": "#4CAF50",
      "success": "#8BC34A",
      "warning": "#FFEB3B",
      "error": "#D32F2F"
    },
    {
      "theme": "dracula",
      "color-scheme": "dark",
      "primary": "#bd93f9",
      "primary-content": "#282a36",
      "secondary": "#ff79c6",
      "accent": "#ffb86c",
      "neutral": "#44475a",
      "base-100": "#282a36",
      "info": "#8be9fd",
      "success": "#50fa7b",
      "warning": "#f1fa8c",
      "error": "#ff5555"
    },
    {
      "theme": "winter",
      "color-scheme": "light",
      "primary": "#1fb6ff",
      "primary-content": "#FFFFFF",
      "secondary": "#5352ed",
      "accent": "#ff7f50",
      "neutral": "#c8d6e5",
      "base-100": "#f1f2f6",
      "info": "#2ed573",
      "success": "#1e90ff",
      "warning": "#ffdd59",
      "error": "#ff4757"
    }
  ]
  